version: '3.9'
services:
  mongo_db:
    container_name: db_container
    image : mongo:latest
    restart : always
    # ports:
    #   - '27017:27017'
    volumes : 
      - mongo_db:/data/db
  api:
    build: .
    ports:
      - '8081:8081'
    # evironment:
    #   PORT: 5000
    #   MONGO_URL: mongodb://mongo_db:27017/databaseof_laptop
    depends_on:
      - mongo_db
volumes:
  mongo_db: {}

